name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t pedidos ./pedidos
          docker build -t pagamentos ./pagamentos
          docker build -t estoque ./estoque
          docker build -t gateway ./gateway

      - name: Run basic tests
        run: echo "Testes executados com sucesso"

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push images
        run: echo "Simulação de push"