name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/pedidos:latest ./pedidos
          docker build -t ${{ secrets.DOCKER_USER }}/pagamentos:latest ./pagamentos
          docker build -t ${{ secrets.DOCKER_USER }}/estoque:latest ./estoque
          docker build -t ${{ secrets.DOCKER_USER }}/gateway:latest ./gateway

      - name: Run basic tests
        run: echo "Testes executados com sucesso"

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USER }}/pedidos:latest
          docker push ${{ secrets.DOCKER_USER }}/pagamentos:latest
          docker push ${{ secrets.DOCKER_USER }}/estoque:latest
          docker push ${{ secrets.DOCKER_USER }}/gateway:latest